surface_colors:
    Clay: firebrick 
    Grass : seagreen
    Hard : midnightblue 
    Carpet : limegreen
  
colors:
    - indianred     
    - seagreen  
    - goldenrod  
    - midnightblue   
    - cadetblue   
    - crimson     
    - darkblue  
    - indigo     
    - lightsalmon   
    - turquoise   
    - magenta

serve_return_cols:
    - 1stIn 
    - 1stWon 
    - 2ndWon 
    - returnWon 
    - ace 
    - df

under_pressure_cols:
    - bpSaved
    - bpConverted
    - tbWon
    - deciderWon


tourney_level_map:
    A: Atp 500
    M: Master 1000
    G: Grand Slam
    F: Finals
    C: Challenger
    D: Davis Cup


rounds:
    - label: Final
      value: F
    - label: Semifinal
      value: SF
    - label: Quarterfinal
      value: QF
    - label: R16
      value: R16
    - label: R32
      value: R32
    - label: R64
      value: R64 
    - label: R128
      value: R128 
    - label: Q1
      value: Q1
    - label: Q2
      value: Q2
    - label: Q3
      value: Q3
    - label: RoundRobin
      value: RR    


details_mapping:
    player_name: Player Name
    best_rank: Best Rank
    country_code: Nationality
    birthdate: Birthdate
    age: Age [years]
    hand: Hand
    height: Height [cm]

matches_mapping:
    year: Year 
    tourney_name: Tournament
    tourney_level: Tourney Level
    surface: Surface
    opponent_name: Opponent
    result: Result
    score: Score
    round: Round
    minutes: Minutes
    ace: Aces
    df: DF
    svpt: SvPt
    1stIn: 1stIn
    1stWon: 1stWon
    2ndWon: 2ndWon
    bpSaved: BpSaved
    bpFaced: BpFaced
    returnWon: ReturnWon
    returnPlayed: ReturnPlayed

h2h_mapping:
    opponent_name: Opponent
    matches_played: Played
    matches_won: Won
    win_rate: Winrate
    perc_ace: "% Aces"
    perc_df: " % Double Faults"
    perc_1stIn: "% 1st In"
    perc_1stWon: "% 1st Won"
    perc_2ndWon: "% 2nd Won"
    perc_returnWon: "% Return Won"
    perc_bpConverted: "% BP Converted"
    perc_bpSaved: "% BP Saved"
    perc_tbWon: "% TB Won"
    perc_deciderWon: "% Decider Won"