scraper_settings = {
    't_cols': [
        'tourney_id', 
        'tourney_name', 
        'surface', 
        'draw_size', 
        'tourney_level',
        'tourney_date'
    ],

    'str_cols': [
        'tourney_id', 
        'tourney_name', 
        'surface', 
        'draw_size', 
        'tourney_level',
        'winner_id',
        'winner_entry',
        'winner_seed',
        'winner_name',
        'winner_hand',
        'winner_ioc',
        'loser_id',
        'loser_entry',
        'loser_seed',
        'loser_name',
        'loser_hand',
        'loser_ioc',
        'score',
        'round'
    ],

    'int_cols': [
        'match_num',
        'best_of',
        'minutes',
        'w_ace',
        'w_df',
        'w_svpt',
        'w_1stIn',
        'w_1stWon',
        'w_2ndWon',
        'w_SvGms',
        'w_bpSaved',
        'w_bpFaced',
        'l_ace',
        'l_df',
        'l_svpt',
        'l_1stIn',
        'l_1stWon',
        'l_2ndWon',
        'l_SvGms',
        'l_bpSaved',
        'l_bpFaced',
        'winner_rank',
        'winner_rank_points',
        'loser_rank',
        'loser_rank_points'
    ],

    'float_cols': [
        'winner_age',
        'loser_age',
        'winner_ht',
        'loser_ht'
    ],

    'fill_values': {
        'match_num': 0,
        'best_of': 3,
        'minutes': 0,
        'w_ace': 0,
        'w_df': 0,
        'w_svpt': 0,
        'w_1stIn': 0,
        'w_1stWon': 0,
        'w_2ndWon': 0,
        'w_SvGms': 0,
        'w_bpSaved': 0,
        'w_bpFaced': 0,
        'l_ace': 0,
        'l_df': 0,
        'l_svpt': 0,
        'l_1stIn': 0,
        'l_1stWon': 0,
        'l_2ndWon': 0,
        'l_SvGms': 0,
        'l_bpSaved': 0,
        'l_bpFaced': 0,
        'winner_rank': 999,
        'winner_rank_points': 0,
        'loser_rank': 999,
        'loser_rank_points': 0
    },


    'w_cols': [
        'tourney_id', 
        'tourney_name', 
        'surface', 
        'draw_size', 
        'tourney_level',
        'tourney_date',
        'match_num', 
        'winner_id', 
        'winner_seed', 
        'winner_entry',
        'winner_name', 
        'winner_hand', 
        'winner_ht', 
        'winner_ioc', 
        'winner_age',
        'winner_rank', 
        'winner_rank_points',
        'loser_id',
        'loser_name',
        'loser_rank',
        'score', 
        'best_of', 
        'round',
        'minutes', 
        'w_ace', 
        'w_df', 
        'w_svpt', 
        'w_1stIn', 
        'w_1stWon', 
        'w_2ndWon',
        'w_SvGms', 
        'w_bpSaved', 
        'w_bpFaced',
        'w_percAce', 
        'w_percDf', 
        'w_perc1stIn',
        'w_perc1stWon', 
        'w_perc2ndWon',
        'w_percBpSaved', 
        'w_SvLost', 
        'w_bpTotal',
        'w_bpConverted', 
        'w_percBpConverted', 
        'w_percSvLost',
        'w_returnWon', 
        'l_svpt',
        'w_percReturnWon',
        'w_percServePointsWon',
        'tb_played',
        'tb_winner',
        'decidingSetPlayed'
    ],

    'l_cols': [
        'tourney_id', 
        'tourney_name', 
        'surface', 
        'draw_size', 
        'tourney_level',
        'tourney_date',
        'match_num', 
        'loser_id', 
        'loser_seed', 
        'loser_entry',
        'loser_name', 
        'loser_hand', 
        'loser_ht', 
        'loser_ioc', 
        'loser_age',
        'loser_rank', 
        'loser_rank_points',
        'winner_id',
        'winner_name',
        'winner_rank',
        'score', 
        'best_of', 
        'round',
        'minutes', 
        'l_ace', 
        'l_df', 
        'l_svpt', 
        'l_1stIn', 
        'l_1stWon', 
        'l_2ndWon',
        'l_SvGms', 
        'l_bpSaved', 
        'l_bpFaced',
        'l_percAce', 
        'l_percDf', 
        'l_perc1stIn',
        'l_perc1stWon', 
        'l_perc2ndWon',
        'l_percBpSaved', 
        'l_SvLost', 
        'l_bpTotal',
        'l_bpConverted', 
        'l_percBpConverted', 
        'l_percSvLost',
        'l_returnWon', 
        'w_svpt',
        'l_percReturnWon',
        'l_percServePointsWon',
        'tb_played',
        'tb_loser',
        'decidingSetPlayed'
    ],

    'wl_cols': [
        'tourney_id', 
        'tourney_name', 
        'surface', 
        'draw_size', 
        'tourney_level',
        'tourney_date',
        'match_num', 
        'id', 
        'seed', 
        'entry',
        'player_name', 
        'hand', 
        'ht', 
        'ioc', 
        'age',
        'rank', 
        'rank_points',
        'opponent_id',
        'opponent_name',
        'opponent_rank',
        'score', 
        'best_of', 
        'round',
        'minutes', 
        'ace', 
        'df', 
        'svpt', 
        'firstIn', 
        'firstWon', 
        'secondWon',
        'SvGms', 
        'bpSaved', 
        'bpFaced',
        'perc_ace', 
        'perc_df', 
        'perc_firstIn',
        'perc_firstWon', 
        'perc_secondWon',
        'perc_bpSaved', 
        'SvLost', 
        'bpTotal',
        'bpConverted', 
        'perc_bpConverted', 
        'perc_svLost',
        'returnWon',
        'returnPlayed',
        'perc_returnWon',
        'perc_servePointsWon',
        'tbPlayed',
        'tbWon',
        'decidingSetPlayed'
    ]

}


tennis_player_settings = {
    
    'surface_colors': {
        'Clay':'firebrick', 
        'Grass':'seagreen', 
        'Hard':'midnightblue', 
        'Carpet':'limegreen'
    },
    'colors': [
        'indianred', 
        'seagreen', 
        'goldenrod', 
        'midnightblue', 
        'cadetblue', 
        'crimson', 
        'darkblue', 
        'indigo', 
        'lightsalmon', 
        'turquoise', 
        'magenta'
    ]




}